/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109379-g2eb7151261-20221207"
#endif /* AVUTIL_FFVERSION_H */
